"use client";

import { useEffect, useState } from "react";
import { RefreshCw, Search } from "lucide-react";

export function ActivityReviewPanel({ eventId }: { eventId: string }) {
  const [rows, setRows] = useState<any[]>([]); const [status, setStatus] = useState(""); const [query, setQuery] = useState(""); const [message, setMessage] = useState("");
  async function load() { const params = new URLSearchParams(); if (status) params.set("status", status); if (query) params.set("q", query); const response = await fetch(`/api/admin/challenges/${eventId}/activities?${params}`, { cache: "no-store" }); const data = await response.json(); if (response.ok) setRows(data.activities); }
  useEffect(() => { const timer = setTimeout(load, 350); return () => clearTimeout(timer); }, [eventId, status, query]);
  async function resync(activityId: string) { const response = await fetch(`/api/admin/challenges/${eventId}/activities/${activityId}/resync`, { method: "POST" }); const data = await response.json(); setMessage(response.ok ? "Đã đưa activity vào hàng đợi đồng bộ lại." : data.error); }
  return <section className="mt-6 rounded-2xl border bg-white p-5 shadow-sm md:p-6"><h2 className="text-xl font-bold">Review activity</h2><p className="mt-1 text-sm text-slate-500">Xem lý do loại và yêu cầu tải lại từ Strava sau khi người dùng crop hoặc sửa.</p><div className="mt-4 grid gap-3 md:grid-cols-[1fr_180px]"><label className="relative"><Search className="absolute left-3 top-3.5 h-4 w-4 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Tìm vận động viên..." className="h-11 w-full rounded-xl border pl-9 pr-3" /></label><select value={status} onChange={(e) => setStatus(e.target.value)} className="h-11 rounded-xl border bg-white px-3"><option value="">Tất cả trạng thái</option><option value="ACCEPTED">Hợp lệ</option><option value="ACCEPTED_WITH_CAP">Bị cap</option><option value="REJECTED">Bị loại</option><option value="NEEDS_REVIEW">Cần review</option></select></div>{message && <p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm">{message}</p>}<div className="mt-4 space-y-3">{rows.map((row) => <article key={row.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><strong>{row.activity.user.displayName}</strong><p className="text-sm text-slate-500">{row.activity.name || row.activity.sportType} · {(row.activity.distanceMeters / 1000).toFixed(2)} km · {new Date(row.activity.startDate).toLocaleString("vi-VN")}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${row.status === "REJECTED" ? "bg-red-100 text-red-700" : "bg-emerald-100 text-emerald-700"}`}>{row.status}</span></div>{row.messages.length > 0 && <ul className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{row.messages.map((item: string) => <li key={item}>• {item}</li>)}</ul>}<div className="mt-3 flex items-center justify-between text-xs text-slate-500"><span>GPS: {row.activity.hasGps ? "Có" : "Không"} · HR: {row.activity.hasHeartRate ? "Có" : "Không"} · Rule v{row.ruleVersion}</span><button onClick={() => resync(row.activity.id)} className="inline-flex items-center gap-1 rounded-lg bg-orange-50 px-3 py-2 font-semibold text-orange-700"><RefreshCw className="h-4 w-4" />Đồng bộ lại</button></div></article>)}</div></section>;
}

