"use client";

import { useEffect, useState } from "react";
import { CalendarClock, Plus, Trash2 } from "lucide-react";

const weekdayNames = ["Chủ nhật", "Thứ hai", "Thứ ba", "Thứ tư", "Thứ năm", "Thứ sáu", "Thứ bảy"];
const toMinute = (time: string) => { const [h, m] = time.split(":").map(Number); return h * 60 + m; };
const toTime = (minute: number) => `${String(Math.floor(minute / 60)).padStart(2, "0")}:${String(minute % 60).padStart(2, "0")}`;

export function AdvancedRulesPanel({ eventId, currentRuleset, enablePoints, pointsPerKm, onChanged }: any) {
  const config = currentRuleset.configJson;
  const [windows, setWindows] = useState<any[]>([]);
  const [specialDays, setSpecialDays] = useState<any[]>([]);
  const [options, setOptions] = useState({ policy: config.timeWindows.policy, timeBasis: config.pace.timeBasis, validateFinalPartial: config.pace.validateFinalPartial, minimumFinalPartialMeters: config.pace.minimumFinalPartialMeters, overlapPolicy: config.scoring.overlapPolicy });
  const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { setWindows((currentRuleset.timeWindows ?? []).map((item: any) => ({ weekday: item.weekday, start: toTime(item.startMinute), end: toTime(item.endMinute) }))); setSpecialDays((currentRuleset.specialDays ?? []).map((item: any) => ({ localDate: new Date(item.localDate).toISOString().slice(0, 10), name: item.name, multiplier: Number(item.multiplier) }))); }, [currentRuleset.id]);
  function addWindow() { setWindows([...windows, { weekday: 1, start: "05:00", end: "08:00" }]); }
  function addSpecialDay() { setSpecialDays([...specialDays, { localDate: new Date().toISOString().slice(0, 10), name: "Ngày đặc biệt", multiplier: 2 }]); }
  async function save() {
    setBusy(true); setMessage("");
    try {
      const nextConfig = { ...config, timeWindows: { enabled: windows.length > 0, policy: options.policy, windows: windows.map((item) => ({ weekday: Number(item.weekday), startMinute: toMinute(item.start), endMinute: toMinute(item.end) })) }, pace: { ...config.pace, timeBasis: options.timeBasis, validateFinalPartial: options.validateFinalPartial, minimumFinalPartialMeters: Number(options.minimumFinalPartialMeters) }, scoring: { ...config.scoring, enabled: enablePoints, pointsPerKm: Number(pointsPerKm), overlapPolicy: options.overlapPolicy } };
      const response = await fetch(`/api/admin/challenges/${eventId}/rulesets`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ effectiveFrom: new Date().toISOString(), applicationScope: "FROM_NOW", changeReason: "Cập nhật khung giờ và ngày hệ số", config: nextConfig, specialDays: specialDays.map((day) => ({ ...day, localDate: `${day.localDate}T00:00:00.000Z`, multiplier: Number(day.multiplier) })) }) });
      const data = await response.json(); if (!response.ok) throw new Error(data.error); setMessage("Đã xuất bản ruleset mới."); await onChanged();
    } catch (error) { setMessage(error instanceof Error ? error.message : "Không thể lưu cấu hình"); } finally { setBusy(false); }
  }
  return <section className="mt-6 rounded-2xl border bg-white p-5 shadow-sm md:p-6"><div className="flex items-center gap-3"><CalendarClock className="h-6 w-6 text-blue-600" /><div><h2 className="text-xl font-bold">Khung giờ & hệ số</h2><p className="text-sm text-slate-500">Để trống khung giờ nghĩa là được chạy cả ngày.</p></div></div><div className="mt-5 grid gap-4 md:grid-cols-2"><Select label="Cách xét khung giờ" value={options.policy} onChange={(value) => setOptions({ ...options, policy: value })} options={[["START_TIME_ONLY","Chỉ xét giờ bắt đầu"],["FULL_ACTIVITY_WINDOW","Toàn activity phải trong khung"]]} /><Select label="Thời gian tính pace" value={options.timeBasis} onChange={(value) => setOptions({ ...options, timeBasis: value })} options={[["MOVING_TIME","Moving time"],["ELAPSED_TIME","Elapsed time"]]} /></div><label className="mt-4 flex items-center gap-2 text-sm"><input type="checkbox" checked={options.validateFinalPartial} onChange={(e) => setOptions({ ...options, validateFinalPartial: e.target.checked })} />Kiểm tra pace đoạn km cuối chưa đủ 1 km</label>{options.validateFinalPartial && <label className="mt-2 block max-w-xs text-sm">Đoạn cuối tối thiểu (m)<input type="number" min="100" value={options.minimumFinalPartialMeters} onChange={(e) => setOptions({ ...options, minimumFinalPartialMeters: Number(e.target.value) })} className="mt-1 h-10 w-full rounded-xl border px-3" /></label>}
    <div className="mt-6 flex items-center justify-between"><h3 className="font-bold">Khung giờ theo ngày</h3><button onClick={addWindow} className="inline-flex items-center gap-1 rounded-lg bg-blue-50 px-3 py-2 text-sm font-semibold text-blue-700"><Plus className="h-4 w-4" />Thêm</button></div><div className="mt-3 space-y-2">{windows.map((item, index) => <div key={index} className="grid grid-cols-[1fr_105px_105px_36px] gap-2"><select value={item.weekday} onChange={(e) => setWindows(windows.map((value, i) => i === index ? { ...value, weekday: Number(e.target.value) } : value))} className="rounded-xl border px-2">{weekdayNames.map((name, day) => <option key={day} value={day}>{name}</option>)}</select><input type="time" value={item.start} onChange={(e) => setWindows(windows.map((value, i) => i === index ? { ...value, start: e.target.value } : value))} className="rounded-xl border px-2" /><input type="time" value={item.end} onChange={(e) => setWindows(windows.map((value, i) => i === index ? { ...value, end: e.target.value } : value))} className="rounded-xl border px-2" /><button onClick={() => setWindows(windows.filter((_, i) => i !== index))} className="text-red-600"><Trash2 className="h-4 w-4" /></button></div>)}</div>
    {enablePoints && <><div className="mt-6 flex items-center justify-between"><h3 className="font-bold">Ngày nhân hệ số</h3><button onClick={addSpecialDay} className="inline-flex items-center gap-1 rounded-lg bg-orange-50 px-3 py-2 text-sm font-semibold text-orange-700"><Plus className="h-4 w-4" />Thêm</button></div><Select label="Khi nhiều hệ số trùng nhau" value={options.overlapPolicy} onChange={(value) => setOptions({ ...options, overlapPolicy: value })} options={[["HIGHEST_ONLY","Chỉ lấy hệ số cao nhất"],["STACK_MULTIPLIERS","Nhân chồng các hệ số"]]} /><div className="mt-3 space-y-2">{specialDays.map((item, index) => <div key={index} className="grid grid-cols-[130px_1fr_90px_36px] gap-2"><input type="date" value={item.localDate} onChange={(e) => setSpecialDays(specialDays.map((value, i) => i === index ? { ...value, localDate: e.target.value } : value))} className="rounded-xl border px-2" /><input value={item.name} onChange={(e) => setSpecialDays(specialDays.map((value, i) => i === index ? { ...value, name: e.target.value } : value))} className="rounded-xl border px-2" /><input type="number" min="1" step="0.1" value={item.multiplier} onChange={(e) => setSpecialDays(specialDays.map((value, i) => i === index ? { ...value, multiplier: Number(e.target.value) } : value))} className="rounded-xl border px-2" /><button onClick={() => setSpecialDays(specialDays.filter((_, i) => i !== index))} className="text-red-600"><Trash2 className="h-4 w-4" /></button></div>)}</div></>}
    {message && <p className="mt-4 rounded-xl bg-slate-50 p-3 text-sm">{message}</p>}<button disabled={busy} onClick={save} className="mt-5 w-full rounded-xl bg-blue-600 px-4 py-3 font-bold text-white disabled:opacity-50">{busy ? "Đang lưu..." : "Xuất bản cấu hình nâng cao"}</button></section>;
}
function Select({ label, value, onChange, options }: any) { return <label className="text-sm font-medium">{label}<select value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 h-11 w-full rounded-xl border bg-white px-3">{options.map(([key,text]: string[]) => <option key={key} value={key}>{text}</option>)}</select></label>; }

