"use client";

import { useEffect, useState } from "react";
import { Search, UserMinus, UserPlus } from "lucide-react";

export function ParticipantsManager({ eventId }: { eventId: string }) {
  const [participants, setParticipants] = useState<any[]>([]); const [athletes, setAthletes] = useState<any[]>([]); const [query, setQuery] = useState(""); const [message, setMessage] = useState("");
  async function load() { const response = await fetch(`/api/admin/challenges/${eventId}/participants`, { cache: "no-store" }); const data = await response.json(); if (response.ok) setParticipants(data.participants); }
  useEffect(() => { void load(); }, [eventId]);
  useEffect(() => { const timer = setTimeout(async () => { if (!query.trim()) return setAthletes([]); const response = await fetch(`/api/admin/challenges/athletes?eventId=${eventId}&q=${encodeURIComponent(query)}`, { cache: "no-store" }); const data = await response.json(); if (response.ok) setAthletes(data.athletes); }, 400); return () => clearTimeout(timer); }, [query, eventId]);
  async function add(userId: string) { const response = await fetch(`/api/admin/challenges/${eventId}/participants`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ userId, activeFrom: new Date().toISOString() }) }); const data = await response.json(); setMessage(response.ok ? "Đã thêm người chơi." : data.error); if (response.ok) { setQuery(""); setAthletes([]); await load(); } }
  async function remove(userId: string) { const reason = window.prompt("Lý do xóa khỏi sự kiện:"); if (!reason?.trim()) return; const response = await fetch(`/api/admin/challenges/${eventId}/participants/${userId}`, { method: "DELETE", headers: { "content-type": "application/json" }, body: JSON.stringify({ reason, leftAt: new Date().toISOString() }) }); const data = await response.json(); setMessage(response.ok ? "Đã xóa khỏi sự kiện." : data.error); if (response.ok) await load(); }
  return <section className="mt-6 rounded-2xl border bg-white p-5 shadow-sm md:p-6"><h2 className="text-xl font-bold">Người tham gia</h2><p className="mt-1 text-sm text-slate-500">Thêm cá nhân trực tiếp; người thuộc đội cũng xuất hiện tại đây.</p><div className="relative mt-4"><Search className="absolute left-3 top-3.5 h-4 w-4 text-slate-400" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Tìm tài khoản đã kết nối Strava..." className="h-11 w-full rounded-xl border pl-9 pr-3" /></div>{athletes.length > 0 && <div className="mt-2 rounded-xl border p-1 shadow-lg">{athletes.map((athlete) => { const enrolled = athlete.enrollments?.length > 0; return <div key={athlete.id} className="flex items-center justify-between rounded-lg px-3 py-2 hover:bg-slate-50"><span>{athlete.displayName}</span><button disabled={enrolled} onClick={() => add(athlete.id)} className="rounded-lg p-2 text-orange-700 disabled:opacity-30"><UserPlus className="h-4 w-4" /></button></div>; })}</div>}{message && <p className="mt-3 text-sm text-slate-600">{message}</p>}<div className="mt-4 overflow-auto rounded-xl border"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="p-3">Vận động viên</th><th className="p-3">Giới tính</th><th className="p-3">Đội</th><th className="p-3">Trạng thái</th><th></th></tr></thead><tbody>{participants.map((item) => <tr key={item.id} className="border-t"><td className="p-3 font-medium">{item.user.displayName}</td><td className="p-3">{item.user.gender}</td><td className="p-3">{item.teamMemberships[0]?.team.name ?? "Cá nhân"}</td><td className="p-3">{item.status}</td><td className="p-3">{item.status === "ACTIVE" && <button onClick={() => remove(item.userId)} className="rounded-lg p-2 text-red-600 hover:bg-red-50"><UserMinus className="h-4 w-4" /></button>}</td></tr>)}</tbody></table></div></section>;
}

