"use client";

import { useState } from "react";
import { FlaskConical } from "lucide-react";

export function RuleSimulator({ eventId }: { eventId: string }) {
  const [form, setForm] = useState({ distanceKm: 5, paceSecondsPerKm: 360, hasGps: true, hasGpsStream: true, hasHeartRate: true, hasHeartRateStream: true, startDate: new Date().toISOString().slice(0, 16) }); const [result, setResult] = useState<any>(null);
  async function simulate() { const response = await fetch(`/api/admin/challenges/${eventId}/rulesets/simulate`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...form, startDate: new Date(form.startDate).toISOString() }) }); const data = await response.json(); setResult(response.ok ? data.result : { status: "ERROR", messages: [data.error] }); }
  return <section className="mt-6 rounded-2xl border bg-white p-5 shadow-sm md:p-6"><div className="flex items-center gap-3"><FlaskConical className="h-6 w-6 text-violet-600" /><div><h2 className="text-xl font-bold">Mô phỏng luật chơi</h2><p className="text-sm text-slate-500">Không ghi dữ liệu hay ảnh hưởng bảng xếp hạng.</p></div></div><div className="mt-4 grid gap-3 md:grid-cols-3"><Field label="Quãng đường (km)" type="number" value={form.distanceKm} onChange={(v) => setForm({ ...form, distanceKm: Number(v) })} /><Field label="Pace (giây/km)" type="number" value={form.paceSecondsPerKm} onChange={(v) => setForm({ ...form, paceSecondsPerKm: Number(v) })} /><Field label="Thời điểm chạy" type="datetime-local" value={form.startDate} onChange={(v) => setForm({ ...form, startDate: v })} /></div><div className="mt-3 flex flex-wrap gap-4">{[["hasGps","Có GPS"],["hasGpsStream","GPS stream"],["hasHeartRate","Có nhịp tim"],["hasHeartRateStream","HR stream"]].map(([key,label]) => <label key={key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={(form as any)[key]} onChange={(e) => setForm({ ...form, [key]: e.target.checked })} />{label}</label>)}</div><button onClick={simulate} className="mt-4 rounded-xl bg-violet-600 px-5 py-2.5 font-bold text-white">Chạy mô phỏng</button>{result && <div className={`mt-4 rounded-xl p-4 ${result.status === "REJECTED" || result.status === "ERROR" ? "bg-red-50 text-red-700" : "bg-emerald-50 text-emerald-700"}`}><strong>{result.status === "ACCEPTED" ? "Activity hợp lệ" : result.status === "ACCEPTED_WITH_CAP" ? "Hợp lệ nhưng bị giới hạn" : "Activity không được ghi nhận"}</strong>{result.messages?.map((message: string) => <p key={message} className="mt-1 text-sm">• {message}</p>)}{result.status?.startsWith("ACCEPTED") && <p className="mt-2 text-sm">Cá nhân: {(result.creditedIndividualMeters / 1000).toFixed(2)} km · Đội: {(result.creditedTeamMeters / 1000).toFixed(2)} km</p>}</div>}</section>;
}
function Field({ label, value, onChange, type }: any) { return <label className="text-sm font-medium">{label}<input type={type} value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 h-11 w-full rounded-xl border px-3" /></label>; }

