"use client";
import { useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { ArrowLeft, Search } from "lucide-react";
const money = (n: number) => new Intl.NumberFormat("vi-VN").format(n) + " đ";
export default function KidRunLookupPage() {
  const { slug } = useParams<{ slug: string }>();
  const [lookup, setLookup] = useState(""); const [secretCode, setSecretCode] = useState(""); const [data, setData] = useState<any>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setLoading(true); setError(""); const res = await fetch("/api/kid-run-applications/lookup", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ slug, lookup, secretCode }) }); const result = await res.json(); setLoading(false); if (!res.ok) return setError(result.error); setData(result); };
  return <main className="min-h-screen bg-slate-50 p-4 md:p-8"><div className="mx-auto max-w-2xl"><Link href={`/kid-run/${slug}`} className="inline-flex items-center gap-2 text-blue-700"><ArrowLeft className="h-4 w-4" />Quay lại đăng ký</Link><div className="mt-5 rounded-lg border bg-white p-6 shadow-sm"><h1 className="text-2xl font-bold">Tra cứu hồ sơ Mid-Autumn Kids Runs</h1><form onSubmit={submit} className="mt-5 space-y-4"><label className="block text-sm font-medium">Email hoặc số điện thoại<input required value={lookup} onChange={(e) => setLookup(e.target.value)} className="mt-1 h-11 w-full rounded-md border px-3" /></label><label className="block text-sm font-medium">Mã bí mật trong email<input required value={secretCode} onChange={(e) => setSecretCode(e.target.value)} className="mt-1 h-11 w-full rounded-md border px-3" /></label><button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-md bg-blue-600 py-3 font-bold text-white"><Search className="h-5 w-5" />{loading ? "Đang tra cứu..." : "Tra cứu"}</button></form>{error && <div className="mt-4 rounded-md bg-red-50 p-3 text-red-700">{error}</div>}</div>{data && <section className="mt-5 rounded-lg border bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">{data.campaign.name}</h2><p className="mt-1">Mã hồ sơ: <b>{data.application.publicCode}</b></p><div className="mt-5 space-y-3">{data.application.participants.map((p: any, i: number) => <div key={p.id} className="rounded-md border p-4"><b>{p.bibNumber ? `BIB ${i + 1}: ${p.bibNumber}` : `Bé ${i + 1}: Chờ cấp BIB`}</b><div>{p.fullName}</div><div className="text-sm text-slate-600">{p.category.name === "__UNASSIGNED__" ? "BTC đang rà soát nhóm tuổi" : `${p.category.name} · ${p.category.distanceLabel}`}</div>{p.shirts.length > 0 && <div className="mt-2 text-sm">Áo: {p.shirts.map((s: any) => `${s.styleName} size ${s.size}`).join(", ")}</div>}</div>)}</div><div className="mt-5 border-t pt-4"><div>Tiền áo: <b>{money(data.application.shirtTotalAmount)}</b></div><div>Trạng thái: <b className={data.application.shirtPaymentStatus === "PAID" ? "text-emerald-700" : "text-amber-700"}>{data.application.shirtPaymentStatus}</b></div></div></section>}</div></main>;
}